# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e6d88682da9fa0190350f032bb8e01d747d4f009e99ae42871c1e2e27a841553f767bb2c08f245e9eaf1abeea25cc87c1167df1c1631e01ff03bb28826ce33e1

test:
  secret_key_base: 05f1e171b8e17c858518522b2a8280baa2a5cdafbfaae5130c6123c40ad33976ea887490ddece3933593abd68156325e36c0f4d6fbd7346ccc262b45ae251429

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
